apiVersion: apps/v1
kind: Deployment
metadata:
  name: swint-db
  namespace: swint-system
  labels:
    app: swint-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swint-db
  template:
    metadata:
      labels:
        app: swint-db
    spec:
      imagePullSecrets:
      - name: harbor-swint
      containers:
      - name: swint-db
        image: harbor.svc.dranswer.co.kr/swint/swint-db:c61084b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/pgsql/13/data/
      volumes:
      - name: pgdata
        hostPath:
          path: /data/swint/data
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: swint-db
  namespace: swint-system
spec:
  type: NodePort
  selector:
    app: swint-db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30333

